// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/apiv1.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SaySomethingClient is the client API for SaySomething service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaySomethingClient interface {
	SayHello(ctx context.Context, in *InputSayHello, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
}

type saySomethingClient struct {
	cc grpc.ClientConnInterface
}

func NewSaySomethingClient(cc grpc.ClientConnInterface) SaySomethingClient {
	return &saySomethingClient{cc}
}

func (c *saySomethingClient) SayHello(ctx context.Context, in *InputSayHello, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, "/SaySomething/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaySomethingServer is the server API for SaySomething service.
// All implementations must embed UnimplementedSaySomethingServer
// for forward compatibility
type SaySomethingServer interface {
	SayHello(context.Context, *InputSayHello) (*wrapperspb.StringValue, error)
	mustEmbedUnimplementedSaySomethingServer()
}

// UnimplementedSaySomethingServer must be embedded to have forward compatible implementations.
type UnimplementedSaySomethingServer struct {
}

func (UnimplementedSaySomethingServer) SayHello(context.Context, *InputSayHello) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSaySomethingServer) mustEmbedUnimplementedSaySomethingServer() {}

// UnsafeSaySomethingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaySomethingServer will
// result in compilation errors.
type UnsafeSaySomethingServer interface {
	mustEmbedUnimplementedSaySomethingServer()
}

func RegisterSaySomethingServer(s grpc.ServiceRegistrar, srv SaySomethingServer) {
	s.RegisterService(&SaySomething_ServiceDesc, srv)
}

func _SaySomething_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputSayHello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaySomethingServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SaySomething/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaySomethingServer).SayHello(ctx, req.(*InputSayHello))
	}
	return interceptor(ctx, in, info, handler)
}

// SaySomething_ServiceDesc is the grpc.ServiceDesc for SaySomething service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaySomething_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SaySomething",
	HandlerType: (*SaySomethingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SaySomething_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/apiv1.proto",
}
